
import java.awt.Font;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felipe
 */
public class LeitorDePensamentos extends javax.swing.JFrame {

    /**
     * Creates new form LeitorDePensamentos
     */
    public LeitorDePensamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblFala = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        txtPalpite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Akinator.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        lblFala.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFala.setText("<html> Estou pensando em um número entre <b>1 e 5</b>. Tente adivinhar que valor é esse.</html>");
        lblFala.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 170, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/balloon.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Valor:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        spnValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spnValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 50, 20));

        txtPalpite.setText("Palpite");
        txtPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(txtPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalpiteActionPerformed
        int rn = (int) (1+(Math.random()*(5-1)));
        
        int palpite = (int) spnValor.getValue();
        
        String s1 = "<html>ACERTOU!</html>";
        String s2 = "<html>Errou!<br>Eu pensei no número "+rn+"!</html>";
        
        if (rn == palpite){
        lblFala.setFont(new Font("Tahoma", Font.BOLD,30));
        lblFala.setText(s1);
        }
        else{
            lblFala.setFont(new Font("Tahoma",Font.PLAIN,15));
            lblFala.setText(s2);
        }
    }//GEN-LAST:event_txtPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeitorDePensamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeitorDePensamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeitorDePensamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeitorDePensamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeitorDePensamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFala;
    private javax.swing.JSpinner spnValor;
    private javax.swing.JButton txtPalpite;
    // End of variables declaration//GEN-END:variables
}
